#created by Apache Tomcat Maven plugin
#Tue Mar 17 18:39:50 EDT 2026
connectorhttpProtocol=HTTP/1.1
enableNaming=true
wars=.war|/
generationTimestamp=1773787190008
accessLogValveFormat=%h %l %u %t %r %s %b %I %D
useServerXml=false
